### ISSUE TITLE
tut2-memory optimization issue

### ISSUE THREAD

**Issue by francozappa** [monosource/radare2-explorations-binaries#1]
Hi,

I would change `gcc` optimization option to `-O1` [here](https://github.com/monosource/radare2-explorations-binaries/blob/master/tut2-memory/Makefile#L4)
to prevent `gcc` from replacing the for loop with an optimized sequence of single machine instructions.

Thanks for sharing this repo 👍

**Comment by monosource** [comment]
Thank you kindly for the catch! I have no idea why that -O3 was left there, it was never my intention.
